/* ============================================================
   LoRA 中英对照词典
   用户输入中文 -> 自动替换为训练用的英文标签
   ============================================================ */

const LORA_DICT = {
  // ---------- 角色/主体 ----------
  '男孩': '1boy',
  '女孩': '1girl',
  '动物': 'animal',
  '天使翅膀': 'angel wings',
  '动物耳朵': 'animal ears',
  '动物鼻子': 'animal nose',
  '鹿角': 'antlers',
  '宇航员': 'astronaut',
  '蝙蝠翅膀': 'bat wings',
  '鸟嘴': 'beak',
  '胡子': 'beard',
  '蜜蜂': 'bee',
  '鸟': 'bird',
  '黑眼睛': 'black eyes',
  '黑头发': 'black hair',
  '金发': 'blonde hair',
  '蓝眼睛': 'blue eyes',
  '棕眼睛': 'brown eyes',
  '棕头发': 'brown hair',
  '蝴蝶': 'butterfly',
  '花布': 'calico',
  '三色猫': 'calico',
  '猫': 'cat',
  '人偶': 'character doll',
  '小孩': 'child',
  '爪子': 'claws',
  '鳄鱼': 'crocodilian',
  '鹿': 'deer',
  '鹿耳': 'deer ears',
  '鹿尾': 'deer tail',
  '恐龙': 'dinosaur',
  '狗': 'dog',
  '玩偶': 'doll',
  '海豚': 'dolphin',
  '龙': 'dragon',
  '东方龙': 'eastern dragon',
  '尖牙': 'fangs',
  '鱼': 'fish',
  '狐狸': 'fox',
  '狐狸耳朵': 'fox ears',
  '狐狸尾巴': 'fox tail',
  '青蛙': 'frog',
  '毛皮': 'fur',
  '兽人': 'furry',
  '女兽人': 'furry female',
  '马': 'horse',
  '昆虫翅膀': 'insect wings',
  '锦鲤': 'koi',
  '舞狮': 'lion dance',
  '蜥蜴': 'lizard',
  '猴子': 'monkey',
  '多尾巴': 'multiple tails',
  '蘑菇': 'mushroom',
  '无人类': 'no humans',
  '猫头鹰': 'owl',
  '熊猫': 'panda',
  '企鹅': 'penguin',
  '花瓣': 'petals',
  '植物': 'plant',
  '蛇颈龙': 'plesiosaur',
  '兔子': 'rabbit',
  '驯鹿': 'reindeer',
  '公鸡': 'rooster',
  '龍脈': 'ryuuki (hydrangea)',
  '紫阳花': 'ryuuki (hydrangea)',
  '蛇': 'snake',
  '雪花': 'snowflakes',
  '星星': 'star (symbol)',
  '毛绒动物': 'stuffed animal',
  '填充玩具': 'stuffed toy',
  '老虎': 'tiger',
  '舌头': 'tongue',
  '乌龟': 'turtle',
  '白色毛皮': 'white fur',
  '白色翅膀': 'white wings',
  '翅膀': 'wings',
  '女巫': 'witch',
  '虎年': 'year of the tiger',

  // ---------- 服饰/装扮 ----------
  '围裙': 'apron',
  '背包': 'backpack',
  '包': 'bag',
  '蓝色鞋': 'blue footwear',
  '蓝色头饰': 'blue headwear',
  '蓝袍': 'blue robe',
  '蓝色短裤': 'blue shorts',
  '领结': 'bowtie',
  '手镯': 'bracelet',
  '新娘头纱': 'bridal veil',
  '新娘': 'bride',
  '厨师': 'chef',
  '厨师帽': 'chef hat',
  '中国服饰': 'chinese clothes',
  '斗篷': 'cloak',
  '衣服': 'clothes',
  '小丑': 'clown',
  '有领连衣裙': 'collared dress',
  '连衣裙': 'dress',
  '耳罩': 'earmuffs',
  '耳环': 'earrings',
  '皮草外套': 'fur coat',
  '汉服': 'hanfu',
  '帽子': 'hat',
  '头盔': 'helmet',
  '角': 'horns',
  '和服': 'japanese clothes',
  '首饰': 'jewelry',
  '项链': 'necklace',
  '和服腰带': 'obi',
  '橙色毛皮': 'orange fur',
  '粉色连衣裙': 'pink dress',
  '粉色和服': 'pink kimono',
  '蓬松短袖': 'puffy short sleeves',
  '蓬松袖': 'puffy sleeves',
  '紫色头饰': 'purple headwear',
  '麒麟': 'qilin (mythology)',
  '红色蝴蝶结': 'red bow',
  '红色领结': 'red bowtie',
  '红色连衣裙': 'red dress',
  '红色和服': 'red kimono',
  '红色裤子': 'red pants',
  '红色围巾': 'red scarf',
  '红色衬衫': 'red shirt',
  '长袍': 'robe',
  '凉鞋': 'sandals',
  '围巾': 'scarf',
  '学生帽': 'school hat',
  '披肩': 'shawl',
  '衬衫': 'shirt',
  '短袖': 'short sleeves',
  '短裤': 'shorts',
  '独角': 'single horn',
  '太空服': 'spacesuit',
  '王冠': 'tiara',
  '面纱': 'veil',
  '魔杖': 'wand',
  '手表': 'watch',
  '婚纱': 'wedding dress',
  '白色连衣裙': 'white dress',
  '冬装': 'winter clothes',
  '女巫帽': 'witch hat',
  '腕表': 'wristwatch',
  '黄色头饰': 'yellow headwear',

  // ---------- 动作/姿势 ----------
  '闭眼': 'closed eyes',
  '闭嘴': 'closed mouth',
  '跳舞': 'dancing',
  '面向观众': 'facing viewer',
  '拿着': 'holding',
  '抱着动物': 'holding animal',
  '拿着书': 'holding book',
  '拿着花束': 'holding bouquet',
  '拿着杯子': 'holding cup',
  '拿着扇子': 'holding fan',
  '拿着花': 'holding flower',
  '拿着乐器': 'holding instrument',
  '拿着勺子': 'holding spoon',
  '拿着法杖': 'holding staff',
  '长发': 'long hair',
  '长袖': 'long sleeves',
  '看着观众': 'looking at viewer',
  '打开的书': 'open book',
  '张嘴': 'open mouth',
  '双手合十': 'own hands together',
  '演奏乐器': 'playing instrument',
  '坐着': 'sitting',
  '微笑': 'smile',
  '站立': 'standing',
  '上半身': 'upper body',

  // ---------- 物品/道具 ----------
  '气球': 'balloon',
  '竹子': 'bamboo',
  '书': 'book',
  '花束': 'bouquet',
  '碗': 'bowl',
  '树枝': 'branch',
  '花蕾': 'bud',
  '虫子': 'bug',
  '杯子': 'cup',
  '水仙花': 'daffodil',
  '扇子': 'fan',
  '长笛': 'flute',
  '折扇': 'folding fan',
  '食物': 'food',
  '叉子': 'fork',
  '手扇': 'hand fan',
  '乐器': 'instrument',
  '勺子': 'ladle',
  '灯笼': 'lantern',
  '叶子': 'leaf',
  '百合花': 'lily (flower)',
  '睡莲叶': 'lily pad',
  '百合白': 'lily white',
  '莲花': 'lotus',
  '月亮': 'moon',
  '牵牛花': 'morning glory',
  '面条': 'noodles',
  '兰花': 'orchid',
  '盘子': 'plate',
  '梅花': 'plum blossoms',
  '红玫瑰': 'red rose',
  '玫瑰': 'rose',
  '法杖': 'staff',
  '蒸汽': 'steam',
  '向日葵': 'sunflower',
  '茶': 'tea',
  '茶杯': 'teacup',
  '泰迪熊': 'teddy bear',
  '郁金香': 'tulip',
  '水': 'water',
  '白色花': 'white flower',
  '白玫瑰': 'white rose',
  '紫藤': 'wisteria',

  // ---------- 修饰/属性 ----------
  '亚洲人': 'asian',
  '脸红': 'blush',
  '腮红贴': 'blush stickers',
  '蝴蝶结': 'bow',
  '乳房': 'breasts',
  '迷彩': 'camouflage',
  '迷彩印花': 'camouflage print',
  '樱花': 'cherry blossoms',
  '菊花': 'chrysanthemum',
  '云': 'cloud',
  '新月': 'crescent',
  '换装': 'crossdressing',
  '花': 'flower',
  '花环项链': 'flower necklace',
  '花卉印花': 'floral print',
  '眼镜': 'glasses',
  '草': 'grass',
  '发髻': 'hair bun',
  '发花': 'hair flower',
  '发饰': 'hair ornament',
  '开心': 'happy',
  '高跟鞋': 'high heels',
  '室内': 'indoors',
  '嘴唇': 'lips',
  '化妆': 'makeup',
  '多彩头发': 'multicolored hair',
  '年老': 'old',
  '老人': 'old man',
  '老妇人': 'old woman',
  '部分淹没': 'partially submerged',
  '肖像': 'portrait',
  '彩虹头发': 'rainbow hair',
  '红唇': 'red lips',
  '红鼻子': 'red nose',
  '影子': 'shadow',
  '短发': 'short hair',
  '简单背景': 'simple background',
  '单人': 'solo',
  '汤': 'soup',
  '正面': 'straight-on',
  '静物': 'still life',
  '牙齿': 'teeth',
  '吐舌': 'tongue out',
  '传统媒体': 'traditional media',
  '皱纹皮肤': 'wrinkled skin',
  '黄色眼睛': 'yellow eyes',
  '黄色花': 'yellow flower',

  // ---------- 其他 ----------
  '蓝色花': 'blue flower',
  '蓝色头饰': 'blue headwear',
  '山茶': 'camellia',
  '水仙': 'daffodil',
  '桃子': 'peach',
  '粉色花': 'pink flower',
  '粉玫瑰': 'pink rose',
  '紫色花': 'purple flower',
  '红色花': 'red flower'
};

/* ============================================================
   词典查找与追加
   - 按中文长度从长到短排序，确保最长匹配优先
   - 保留用户原始输入不变，将匹配到的英文标签追加在末尾
   ============================================================ */
(function () {
  // 预排序：中文键从长到短
  const sortedEntries = Object.entries(LORA_DICT).sort(
    (a, b) => b[0].length - a[0].length
  );

  /**
   * 保留原始输入，追加匹配到的英文标签
   * @param {string} input 用户原始输入
   * @returns {string} 原始文本 + 逗号分隔的英文标签
   */
  function translatePrompt(input) {
    if (!input) return '';

    const original = input;
    const found = [];
    const seen = new Set();

    for (const [zh, en] of sortedEntries) {
      if (seen.has(en)) continue;
      const escaped = zh.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
      const re = new RegExp(escaped, 'g');
      if (re.test(input)) {
        found.push(en);
        seen.add(en);
      }
    }

    if (found.length === 0) return original;
    return `${original}, ${found.join(', ')}`;
  }

  // 暴露到全局
  window.LORA_TRANSLATE = translatePrompt;
})();
